# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Lazytorrent < Formula
  desc "A lazygit-style terminal UI for torrents over transmission-daemon"
  homepage "https://github.com/hansbala/lazytorrent"
  version "0.1.3"
  license "MIT"

  depends_on "transmission-cli"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/hansbala/lazytorrent/releases/download/v0.1.3/lazytorrent_0.1.3_darwin_x86_64.tar.gz"
      sha256 "bf19d4be05a1516c800eb5ae626958328639e57b8c9e5bb653fabfc3a2c31cd2"

      define_method(:install) do
        bin.install "lazytorrent"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/hansbala/lazytorrent/releases/download/v0.1.3/lazytorrent_0.1.3_darwin_arm64.tar.gz"
      sha256 "0a4ac54556e97b9543a686083e7d8f22eae70611757801df597a3d1395b0688c"

      define_method(:install) do
        bin.install "lazytorrent"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/hansbala/lazytorrent/releases/download/v0.1.3/lazytorrent_0.1.3_linux_x86_64.tar.gz"
      sha256 "68345fda7d2035d0e204489d62841f4839dbb56a13734a3b8c17e6d10be5e2fe"
      define_method(:install) do
        bin.install "lazytorrent"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/hansbala/lazytorrent/releases/download/v0.1.3/lazytorrent_0.1.3_linux_arm64.tar.gz"
      sha256 "bb34499376c20bc5ba89ca236e8ca85eca260b2f4539918256e1c39cc9c4a1d8"
      define_method(:install) do
        bin.install "lazytorrent"
      end
    end
  end

  test do
    system "#{bin}/lazytorrent", "--version"
  end
end
