# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Lazytorrent < Formula
  desc "A lazygit-style terminal UI for torrents over transmission-daemon"
  homepage "https://github.com/hansbala/lazytorrent"
  version "0.1.2"
  license "MIT"

  depends_on "transmission-cli"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/hansbala/lazytorrent/releases/download/v0.1.2/lazytorrent_0.1.2_darwin_x86_64.tar.gz"
      sha256 "5f2e37af1fc3ba8ea8994800145edb8eb0d6b20b96a7d9c649e65cf485eecb85"

      define_method(:install) do
        bin.install "lazytorrent"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/hansbala/lazytorrent/releases/download/v0.1.2/lazytorrent_0.1.2_darwin_arm64.tar.gz"
      sha256 "ef296ec53449bd5475bfae8c558e19d2f64d98e068088a3f7d3fe1e9fca9a217"

      define_method(:install) do
        bin.install "lazytorrent"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/hansbala/lazytorrent/releases/download/v0.1.2/lazytorrent_0.1.2_linux_x86_64.tar.gz"
      sha256 "18d51cb88db720f1bacaddda9ab8a3850a74acf7e37a6ec97c6101c3132f4ca4"
      define_method(:install) do
        bin.install "lazytorrent"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/hansbala/lazytorrent/releases/download/v0.1.2/lazytorrent_0.1.2_linux_arm64.tar.gz"
      sha256 "075fd0ea96613868ce57a65938aaf7d03f8a098398bdb0249a13a56053ed7704"
      define_method(:install) do
        bin.install "lazytorrent"
      end
    end
  end

  test do
    system "#{bin}/lazytorrent", "--version"
  end
end
